"""replace response_type with actual media type

Revision ID: 0ba5a33099a0
Revises: e09c497d9188
Create Date: 2023-11-27 15:33:59.104545

"""

# revision identifiers, used by Alembic.
revision = '0ba5a33099a0'
down_revision = 'e09c497d9188'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('response_media_type', sa.String(), default='application/json', nullable=True))
    op.drop_column('rule', 'response_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('response_type', postgresql.ENUM('xml', 'json', 'text', name='response_types'), autoincrement=False, nullable=True))
    op.drop_column('rule', 'response_media_type')
    # ### end Alembic commands ###