"""add rules table

Revision ID: 17468194e2a4
Revises: 
Create Date: 2022-09-20 13:09:17.084320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17468194e2a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('call_backend', sa.Boolean(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule')
    # ### end Alembic commands ###
