"""replace response as json

Revision ID: 1be6750e9453
Revises: 57fec8f3b8ff
Create Date: 2023-03-08 17:02:48.534999

"""
from alembic import op
import sqlalchemy as sa
import os

# revision identifiers, used by Alembic.
revision = '1be6750e9453'
down_revision = '57fec8f3b8ff'
branch_labels = None
depends_on = None


def upgrade():
    db_type = os.getenv("DB_TYPE", "sqlite").lower()

    if db_type == "sqlite":
        # SQLite doesn't support ALTER COLUMN with type change, skip for SQLite
        # The response column will remain as String but can store JSON-like strings
        pass
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('rule', 'response', type_=sa.JSON(), nullable=True, postgresql_using='response::json')
        # ### end Alembic commands ###


def downgrade():
    db_type = os.getenv("DB_TYPE", "sqlite").lower()

    if db_type == "sqlite":
        # No-op for SQLite
        pass
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('rule', 'response', type_=sa.String(), nullable=True)
        # ### end Alembic commands ###
