"""replace response as json

Revision ID: 1be6750e9453
Revises: 57fec8f3b8ff
Create Date: 2023-03-08 17:02:48.534999

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1be6750e9453'
down_revision = '57fec8f3b8ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rule', 'response', type_=sa.JSON(), nullable=True, postgresql_using='response::json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rule', 'response', type_=sa.String(), nullable=True)
    # ### end Alembic commands ###
