"""add description

Revision ID: 5474c59c1e90
Revises: 0ba5a33099a0
Create Date: 2025-01-14 14:46:49.733437

"""

# revision identifiers, used by Alembic.
revision = '5474c59c1e90'
down_revision = '0ba5a33099a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'description')
    # ### end Alembic commands ###