"""add rules custom_headrs

Revision ID: 57fec8f3b8ff
Revises: 703ac37a01ab
Create Date: 2022-12-02 12:35:04.536486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57fec8f3b8ff'
down_revision = '703ac37a01ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('custom_headers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'custom_headers')
    # ### end Alembic commands ###
