"""add rules response delay

Revision ID: 703ac37a01ab
Revises: ae92739891d7
Create Date: 2022-11-30 13:59:08.090069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703ac37a01ab'
down_revision = 'ae92739891d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('response_delay', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'response_delay')
    # ### end Alembic commands ###
