"""add rules mock count

Revision ID: ae92739891d7
Revises: 17468194e2a4
Create Date: 2022-10-27 17:58:55.476435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae92739891d7'
down_revision = '17468194e2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('mock_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'mock_count')
    # ### end Alembic commands ###
